"""
Project Euler Problem 45
========================

Triangle, pentagonal, and hexagonal numbers are generated by the following
formulae:

Triangle     T[n]=n(n+1)/2   1, 3, 6, 10, 15, ...
Pentagonal   P[n]=n(3n-1)/2  1, 5, 12, 22, 35, ...
Hexagonal    H[n]=n(2n-1)    1, 6, 15, 28, 45, ...

It can be verified that T[285] = P[165] = H[143] = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
"""

from itertools import islice

from euler.utils.sequences import is_hexagonal, is_pentagonal, triangular


def solution() -> int:
    return next(
        x
        for x in islice(triangular(), 285, None)
        if is_pentagonal(x) and is_hexagonal(x)
    )


if __name__ == "__main__":
    print(solution())
