"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""
from itertools import takewhile

from euler.utils.fibonacci import fibonacci


def solution1() -> int:
    """A simple solution."""
    return sum(x for x in takewhile(lambda n: n < 4000000, fibonacci()) if x % 2 == 0)


if __name__ == "__main__":
    print(solution1())
